import Header from "@/app/components/layout/Header";

import { MapProvider } from "@/contexts/MapContext";
import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen bg-[#191A33] flex flex-col`}>
        <MapProvider>
          <Suspense>
            <Header />
            {children}
          </Suspense>
        </MapProvider>
      </body>
    </html>
  );
}
